### ISSUE TITLE
Add support for multiple wallets

### ISSUE THREAD

**Issue by KanishkKhurana** [Lumos-metaverse/Voting-platform-on-Polygon#7] opened 2023-02-24 13:28 UTC

**Comment by abhinow01** [comment] 2023-03-04 03:49
hey @KanishkKhurana , would like to start with this issue , can you elaborate on the issue a bit more , my understanding of the issue is , we have to enable the app in a way that it can interact with different  wallets

**Comment by tab21** [comment] 2023-03-05 05:09
hi @KanishkKhurana I would like to work on this issue, can this be assigned to me please
I was thinking of using web3modal to be able to connect multiple wallets.

**Closed as completed** 2023-03-15 08:06 UTC
